# Generated by Django 4.1.2 on 2022-10-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_author_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='post',
            field=models.ManyToManyField(null=True, to='api.post'),
        ),
    ]
