# Generated by Django 4.1.2 on 2022-10-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Published'), (3, 'Unpublished')], default=1, max_length=20),
        ),
    ]
