# Generated by Django 4.1.2 on 2022-10-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Published'), (3, 'Unpublished')], default=1),
        ),
    ]
