import type {NextPage} from 'next'
import Head from 'next/head'
import TipTap from "../component/Editor/TipTap";
import axios from "axios";
import {CategoriesResponse} from "../props/CategoryProps";

const Home: NextPage<CategoriesResponse> = ({categories}: CategoriesResponse) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>
        <TipTap categories={categories}/>
      </main>
    </div>
  )
}
export default Home

export async function getServerSideProps() {
   const data = await axios.get('http://localhost:8000/categories/')
    .then((response) => {
        return response.data
    })
    .catch((error) => {
      console.log(error.message)
    })

  return {
    props: {
      categories: data?.results || []
    }
  }
}