import type {NextPage} from 'next'
import Head from 'next/head'
import TipTap from "../component/Editor/TipTap";

const Home: NextPage = () => {


    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <TipTap/>
            </main>


        </div>
    )
}

export default Home
