import type {NextPage} from 'next'
import Head from 'next/head'
import {useEffect, useState} from "react";
import Extensions from '../component/TipTapExtensions'
import {EditorContent, useEditor} from "@tiptap/react";
import styles from '../styles/Post.module.css'

interface MetaData {
    title: string,
    desc: string
}


const Home: NextPage = () => {

    const [metadata, setMetadata] = useState<MetaData | undefined>(undefined)

    const editor = useEditor({
        editable: false,
        extensions: Extensions,
    })

    useEffect(() => {
        const data = window.localStorage.getItem("docs")
        const metaDataLocal = window.localStorage.getItem("metadata")
        if (data != null && metaDataLocal != "") {
            editor?.commands.setContent(JSON.parse(data))
        }

        if (metaDataLocal != null && metaDataLocal != "") {
            setMetadata(JSON.parse(metaDataLocal))
        }

    }, [metadata])


    return (
        <div>
            <Head>
                <title>{metadata?.title}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <div className={styles["blog"]}>
                    <EditorContent editor={editor}/>
                </div>
            </main>


        </div>
    )
}

export default Home
