import type {NextPage} from 'next'
import Head from 'next/head'
import parser from "html-react-parser"
import {useEffect, useMemo, useState} from "react";
import {generateHTML} from "@tiptap/core";
import Extensions from '../component/TipTapExtensions'

interface MetaData {
    title: string,
    desc: string
}


const Home: NextPage = () => {

    const [getBlog, setBlog] = useState("")
    const [metadata, setMetadata] = useState<MetaData|undefined>(undefined)



    useEffect(() => {
        const data = window.localStorage.getItem("docs")
        const metaDataLocal = window.localStorage.getItem("metadata")
        if (data != null) {
            setBlog(data)
        }

        if (metaDataLocal != null && metaDataLocal != "") {
            setMetadata(JSON.parse(metaDataLocal))
        }

    }, [getBlog, metadata])

    const test = useMemo(() => {

        try {
            var json = JSON.parse(getBlog)



            return generateHTML(
                json, Extensions
            )
        } catch (ex) {
            return "<p></p>"
        }
    }, [getBlog])

    var te = parser(test)

    return (
        <div>
            <Head>
                <title>{metadata?.title}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main>
                <div>
                    {
                        te
                    }
                </div>
            </main>


        </div>
    )
}

export default Home
